language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.3
before_install:
  - gem update bundler --no-document
notifications:
  webhooks:
    - https://idobata.io/hook/travis_ci/f7467f11-26df-4e55-9bf0-47f5275d0c76
